allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
patchedDependencies:
  '@readium/navigator-html-injectables@2.4.4': patches/@readium__navigator-html-injectables@2.4.4.patch
  '@readium/navigator@2.6.1': patches/@readium__navigator@2.6.1.patch
